import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { fetchMobileDriver, MobileDriverTrip } from '@/lib/auth';
import { usePassengerAuth } from '@/providers/passenger-auth-provider';

const GREEN='#10B981'; const BG='#F7F9F8'; const SURFACE='#FFFFFF'; const TEXT='#101828'; const MUTED='#667085'; const LINE='#E4E7EC';

function formatDeparture(value:string){return new Intl.DateTimeFormat('en-ZA',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));}

export default function DriverRidesScreen(){
 const router=useRouter(); const {session}=usePassengerAuth();
 const [trips,setTrips]=useState<MobileDriverTrip[]>([]); const [loading,setLoading]=useState(Boolean(session)); const [tab,setTab]=useState<'active'|'history'>('active'); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{if(!session)return;let active=true;fetchMobileDriver(session).then(r=>{if(active)setTrips(r.trips)}).catch((reason:unknown)=>{if(active)setError(reason instanceof Error?reason.message:'Unable to load rides')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[session]);
 const data=useMemo(()=>trips.filter(t=>tab==='active'?!['Completed','Cancelled'].includes(t.status):['Completed','Cancelled'].includes(t.status)),[tab,trips]);
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}>
  <View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.title}>My Rides</Text><Pressable onPress={()=>router.push('/driver-publish')} style={styles.add}><Text style={styles.addText}>＋</Text></Pressable></View>
  <View style={styles.tabs}><Pressable onPress={()=>setTab('active')} style={[styles.tab,tab==='active'&&styles.tabActive]}><Text style={[styles.tabText,tab==='active'&&styles.tabTextActive]}>Upcoming</Text></Pressable><Pressable onPress={()=>setTab('history')} style={[styles.tab,tab==='history'&&styles.tabActive]}><Text style={[styles.tabText,tab==='history'&&styles.tabTextActive]}>Past</Text></Pressable></View>
  {loading?<View style={styles.state}><ActivityIndicator color={GREEN}/></View>:error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:data.length?<View style={styles.list}>{data.map((trip,index)=><Pressable key={trip.id} onPress={()=>router.push({pathname:'/driver-trip/[id]',params:{id:trip.id}})} style={[styles.row,index<data.length-1&&styles.border]}><View style={{flex:1}}><Text style={styles.route}>{trip.route}</Text><Text style={styles.meta}>{formatDeparture(trip.departureAt)} · {trip.status}</Text><Text style={styles.vehicle}>{trip.vehicle||'Vehicle'}{trip.vehicleRegistration?` · ${trip.vehicleRegistration}`:''}</Text></View><View style={styles.right}><Text style={styles.fare}>{trip.fare}</Text><Text style={styles.seats}>{trip.seatsBooked}/{trip.seatCapacity} booked</Text><Text style={styles.chevron}>›</Text></View></Pressable>)}</View>:<View style={styles.state}><Text style={styles.emptyTitle}>{tab==='active'?'No upcoming rides':'No ride history yet'}</Text><Text style={styles.emptyText}>{tab==='active'?'Publish a verified trip and it will appear here.':'Completed and cancelled rides will appear here.'}</Text></View>}
 </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BG},page:{padding:16,paddingBottom:40},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:38,height:38,borderRadius:11,backgroundColor:SURFACE,borderWidth:1,borderColor:LINE,alignItems:'center',justifyContent:'center'},backText:{color:TEXT,fontSize:29,lineHeight:29,marginTop:-3},title:{color:TEXT,fontSize:18,fontWeight:'900'},add:{width:38,height:38,borderRadius:11,backgroundColor:GREEN,alignItems:'center',justifyContent:'center'},addText:{color:'#FFFFFF',fontSize:20,fontWeight:'700'},tabs:{marginTop:16,flexDirection:'row',backgroundColor:'#EEF2F0',padding:3,borderRadius:10},tab:{flex:1,height:36,borderRadius:8,alignItems:'center',justifyContent:'center'},tabActive:{backgroundColor:SURFACE,borderWidth:1,borderColor:LINE},tabText:{color:MUTED,fontSize:8.5,fontWeight:'900'},tabTextActive:{color:'#087F5B'},list:{marginTop:12,backgroundColor:SURFACE,borderWidth:1,borderColor:LINE,borderRadius:15,overflow:'hidden'},row:{minHeight:88,padding:12,flexDirection:'row',alignItems:'center',gap:12},border:{borderBottomWidth:1,borderBottomColor:LINE},route:{color:TEXT,fontSize:10.5,fontWeight:'900'},meta:{color:MUTED,fontSize:8,marginTop:3},vehicle:{color:'#087F5B',fontSize:7.5,fontWeight:'800',marginTop:4},right:{alignItems:'flex-end'},fare:{color:TEXT,fontSize:10,fontWeight:'900'},seats:{color:MUTED,fontSize:7.5,marginTop:3},chevron:{color:'#98A2B3',fontSize:20,marginTop:4},state:{minHeight:180,alignItems:'center',justifyContent:'center',padding:22},emptyTitle:{color:TEXT,fontSize:12,fontWeight:'900'},emptyText:{color:MUTED,fontSize:9,textAlign:'center',marginTop:4},error:{marginTop:14,borderRadius:11,backgroundColor:'#FFF1F0',padding:11},errorText:{color:'#B42318',fontSize:9}});
