"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, Pencil, RefreshCcw, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Booking={id:string;publicId:string;seats:number;amountCents:number;amount:string;paymentStatus:string;status:string;createdAt:string;updatedAt:string};
type Passenger={id:string;name:string;email:string};
type Trip={id:string;databaseId:string;route:string;departure:string;driver:string};
type Payment={ref:string;amount:string;method:string;status:string;created:string};
type Activity={id:string;title:string;detail:string;time:string};

function variant(v:string){const s=v.toLowerCase();if(s.includes("paid")||s.includes("settled")||s.includes("confirmed")||s.includes("completed"))return "success" as const;if(s.includes("pending")||s.includes("awaiting"))return "warning" as const;if(s.includes("cancel")||s.includes("refund")||s.includes("failed"))return "destructive" as const;return "secondary" as const;}

export function BookingDetail({initialBooking,passenger,trip,payments,activity}:{initialBooking:Booking;passenger:Passenger;trip:Trip;payments:Payment[];activity:Activity[]}) {
 const router=useRouter(); const [booking,setBooking]=useState(initialBooking); const [editOpen,setEditOpen]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 async function patch(update:Record<string,unknown>){setSaving(true);setMessage(null);try{const r=await fetch(`/api/admin/bookings/${booking.publicId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(update)});const p=await r.json().catch(()=>null);if(!r.ok){setMessage(p?.error??"Unable to update booking");return false;}setBooking(c=>({...c,...update,status:String(update.status??c.status),paymentStatus:String(update.paymentStatus??c.paymentStatus),updatedAt:new Date().toISOString()} as Booking));router.refresh();return true;}finally{setSaving(false);}}
 async function save(fd:FormData){const ok=await patch({seats:Number(fd.get("seats")),amount:Number(fd.get("amount")),status:String(fd.get("status")||"")});if(ok){setEditOpen(false);setMessage("Booking updated.");}}
 return <div className="min-h-screen bg-[#F7F8FA] text-[#101828]">
 <header className="sticky top-0 z-30 border-b border-[#E4E7EC] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center gap-3 px-4 sm:px-6 lg:px-8"><Button variant="outline" size="icon" render={<Link href="/admin"/>}><ArrowLeft/></Button><div className="min-w-0 flex-1"><div className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#98A2B3]">Vaya CRM / Bookings</div><div className="truncate text-sm font-semibold">{booking.publicId}</div></div><Badge variant={variant(booking.status)}>{booking.status}</Badge><Button variant="outline" onClick={()=>setEditOpen(true)}><Pencil/>Edit</Button></div></header>
 <main className="mx-auto max-w-[1440px] p-4 sm:p-6 lg:p-8">{message?<div className="mb-5 rounded-lg border border-[#D1E9FF] bg-[#F5F9FF] px-4 py-3 text-sm text-[#175CD3]">{message}</div>:null}
 <div className="mb-6 flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><h1 className="text-2xl font-bold tracking-[-.035em] sm:text-[30px]">{booking.publicId}</h1><p className="mt-2 text-sm text-[#667085]">{trip.route} · {passenger.name}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void patch({status:"Confirmed"})}><CheckCircle2/>Confirm booking</Button><Button variant="outline" onClick={()=>void patch({status:"Completed"})}>Complete</Button><Button variant="destructive" onClick={()=>void patch({status:"Cancelled"})}><XCircle/>Cancel</Button></div></div>
 <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="space-y-6">
 <Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Booking details</CardTitle><CardDescription>Reservation, payment and linked customer information.</CardDescription></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3"><Metric label="Passenger" value={passenger.name}/><Metric label="Trip" value={trip.route}/><Metric label="Seats" value={String(booking.seats)}/><Metric label="Amount" value={booking.amount}/><Metric label="Payment" value={booking.paymentStatus}/><Metric label="Status" value={booking.status}/></CardContent></Card>
 <Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Related records</CardTitle><CardDescription>Navigate to the passenger or trip behind this booking.</CardDescription></CardHeader><CardContent className="grid gap-3 p-5 sm:grid-cols-2"><Link className="rounded-lg border border-[#EAECF0] p-4 transition hover:border-[#B7D5FA] hover:bg-[#F8FBFF]" href={`/admin/passengers/${passenger.id}`}><div className="text-xs font-semibold text-[#101828]">{passenger.name}</div><div className="mt-1 text-[11px] text-[#667085]">{passenger.email}</div></Link><Link className="rounded-lg border border-[#EAECF0] p-4 transition hover:border-[#B7D5FA] hover:bg-[#F8FBFF]" href={`/admin/trips/${trip.id}`}><div className="text-xs font-semibold text-[#101828]">{trip.route}</div><div className="mt-1 text-[11px] text-[#667085]">{trip.departure}</div></Link></CardContent></Card>
 <Card className="overflow-hidden shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Payments</CardTitle><CardDescription>{payments.length} payments linked to this booking.</CardDescription></CardHeader>{payments.length?<Table><TableHeader><TableRow className="hover:bg-transparent"><TableHead>Reference</TableHead><TableHead>Amount</TableHead><TableHead>Method</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{payments.map(p=><TableRow key={p.ref}><TableCell><Link className="font-semibold text-[#101828] hover:text-[#1877F2]" href={`/admin/payments/${p.ref}`}>{p.ref}</Link></TableCell><TableCell>{p.amount}</TableCell><TableCell>{p.method}</TableCell><TableCell><Badge variant={variant(p.status)}>{p.status}</Badge></TableCell></TableRow>)}</TableBody></Table>:<Empty/>}</Card>
 </div><div className="space-y-6"><Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Activity</CardTitle><CardDescription>Booking audit history.</CardDescription></CardHeader><ActivityList items={activity}/></Card><Card className="shadow-none"><CardHeader><CardTitle>Lifecycle</CardTitle><CardDescription>Use status changes instead of deleting booking history.</CardDescription></CardHeader><CardContent className="grid gap-2"><Button variant="outline" onClick={()=>void patch({status:"Awaiting payment"})}><RefreshCcw/>Awaiting payment</Button>{payments[0] ? <Button variant="outline" render={<Link href={`/admin/payments/${payments[0].ref}`} />}>Open payment</Button> : null}</CardContent></Card></div></div>
 </main>
 <Dialog open={editOpen} onOpenChange={setEditOpen}><DialogContent><DialogHeader><DialogTitle>Edit booking</DialogTitle><DialogDescription>Update seat count, amount and lifecycle status.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void save(new FormData(e.currentTarget));}}><div className="space-y-4 p-5"><Field label="Seats" id="b-seats"><Input id="b-seats" name="seats" type="number" min="1" max="8" defaultValue={booking.seats} required/></Field><Field label="Amount" id="b-amount"><Input id="b-amount" name="amount" type="number" min="0" step="1" defaultValue={booking.amountCents/100} required/></Field><div className="rounded-lg border border-[#EAECF0] bg-[#F9FAFB] p-3"><div className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#98A2B3]">Payment status</div><div className="mt-2 text-sm font-semibold text-[#344054]">{booking.paymentStatus}</div><div className="mt-1 text-[11px] text-[#667085]">Update this from the linked Payment record.</div></div><Field label="Booking status" id="b-status"><select id="b-status" name="status" defaultValue={booking.status} className="h-9 w-full rounded-lg border border-[#D0D5DD] bg-white px-3 text-sm"><option>Awaiting payment</option><option>Confirmed</option><option>Completed</option><option>Cancelled</option></select></Field></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setEditOpen(false)}>Cancel</Button><Button type="submit" className="bg-[#1877F2]" disabled={saving}>{saving?"Saving...":"Save changes"}</Button></DialogFooter></form></DialogContent></Dialog>
 </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-[#EAECF0] bg-[#F9FAFB] p-4"><div className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#98A2B3]">{label}</div><div className="mt-2 text-sm font-semibold text-[#344054]">{value}</div></div>}
function Field({label,id,children}:{label:string;id:string;children:React.ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
function Empty(){return <div className="grid min-h-28 place-items-center p-6 text-sm text-[#98A2B3]">No related records.</div>}
function ActivityList({items}:{items:Activity[]}){return <CardContent className="divide-y divide-[#EAECF0] p-0">{items.length?items.map(i=><div key={i.id} className="px-5 py-4"><div className="text-xs font-semibold">{i.title}</div><div className="mt-1 text-[11px] text-[#667085]">{i.detail}</div><div className="mt-1 text-[10px] text-[#98A2B3]">{i.time}</div></div>):<div className="p-5 text-xs text-[#98A2B3]">No activity yet.</div>}</CardContent>}
