"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Ban, Mail, MapPin, Pencil, Phone, Trash2, UserCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Passenger={id:string;name:string;email:string;phone:string;city:string;tripsCount:number;status:string;joinedAt:string;updatedAt:string};
type Booking={id:string;tripId:string;route:string;seats:number;amount:string;payment:string;status:string;created:string};
type Payment={ref:string;booking:string;amount:string;method:string;status:string;created:string};
type Activity={id:string;title:string;detail:string;time:string};

function variant(value:string){const v=value.toLowerCase();if(v.includes("active")||v.includes("paid")||v.includes("settled")||v.includes("confirmed")||v.includes("completed"))return "success" as const;if(v.includes("review")||v.includes("pending")||v.includes("awaiting"))return "warning" as const;if(v.includes("suspend")||v.includes("removed")||v.includes("cancel"))return "destructive" as const;return "secondary" as const;}

export function PassengerDetail({initialPassenger,bookings,payments,activity}:{initialPassenger:Passenger;bookings:Booking[];payments:Payment[];activity:Activity[]}) {
 const router=useRouter(); const [passenger,setPassenger]=useState(initialPassenger); const [editOpen,setEditOpen]=useState(false); const [removeOpen,setRemoveOpen]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 async function patch(update:Record<string,unknown>){setSaving(true);setMessage(null);try{const r=await fetch(`/api/admin/passengers/${passenger.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(update)});const p=await r.json().catch(()=>null);if(!r.ok){setMessage(p?.error??"Unable to update passenger");return false;}setPassenger(c=>({...c,...update,updatedAt:new Date().toISOString()} as Passenger));router.refresh();return true;}finally{setSaving(false);}}
 async function save(fd:FormData){const ok=await patch({name:String(fd.get("name")||"").trim(),email:String(fd.get("email")||"").trim(),phone:String(fd.get("phone")||"").trim(),city:String(fd.get("city")||"").trim()});if(ok){setEditOpen(false);setMessage("Passenger profile updated.");}}
 async function remove(){setSaving(true);try{const r=await fetch(`/api/admin/passengers/${passenger.id}`,{method:"DELETE"});if(r.ok){router.push("/admin");router.refresh();}else{const p=await r.json().catch(()=>null);setMessage(p?.error??"Unable to remove passenger");}}finally{setSaving(false);}}
 return <div className="min-h-screen bg-[#F7F8FA] text-[#101828]">
  <header className="sticky top-0 z-30 border-b border-[#E4E7EC] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center gap-3 px-4 sm:px-6 lg:px-8"><Button variant="outline" size="icon" render={<Link href="/admin"/>}><ArrowLeft/></Button><div className="min-w-0 flex-1"><div className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#98A2B3]">Vaya CRM / Passengers</div><div className="truncate text-sm font-semibold">{passenger.name}</div></div><Badge variant={variant(passenger.status)}>{passenger.status}</Badge><Button variant="outline" onClick={()=>setEditOpen(true)}><Pencil/>Edit</Button></div></header>
  <main className="mx-auto max-w-[1440px] p-4 sm:p-6 lg:p-8">{message?<div className="mb-5 rounded-lg border border-[#D1E9FF] bg-[#F5F9FF] px-4 py-3 text-sm text-[#175CD3]">{message}</div>:null}
   <div className="mb-6 flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><h1 className="text-2xl font-bold tracking-[-.035em] sm:text-[30px]">{passenger.name}</h1><div className="mt-2 flex flex-wrap gap-4 text-xs text-[#667085]"><span className="inline-flex items-center gap-1.5"><Mail className="size-3.5"/>{passenger.email}</span><span className="inline-flex items-center gap-1.5"><MapPin className="size-3.5"/>{passenger.city}</span></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void patch({status:"Review"})}>Mark review</Button><Button variant="outline" onClick={()=>void patch({status:"Suspended"})}><Ban/>Suspend</Button><Button className="bg-[#1877F2] hover:bg-[#166FE5]" onClick={()=>void patch({status:"Active"})}><UserCheck/>Activate</Button></div></div>
   <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div className="space-y-6">
    <Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Passenger profile</CardTitle><CardDescription>Contact and customer account information.</CardDescription></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2"><Metric label="Email" value={passenger.email}/><Metric label="Phone" value={passenger.phone||"Not provided"}/><Metric label="Home city" value={passenger.city}/><Metric label="Trips" value={String(passenger.tripsCount)}/></CardContent></Card>
    <Card className="overflow-hidden shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Booking history</CardTitle><CardDescription>{bookings.length} bookings linked to this passenger.</CardDescription></CardHeader>{bookings.length?<Table><TableHeader><TableRow className="hover:bg-transparent"><TableHead>Booking</TableHead><TableHead>Trip</TableHead><TableHead>Seats</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{bookings.map(b=><TableRow key={b.id}><TableCell><Link className="font-semibold text-[#101828] hover:text-[#1877F2]" href={`/admin/bookings/${b.id}`}>{b.id}</Link></TableCell><TableCell><Link className="hover:text-[#1877F2]" href={`/admin/trips/${b.tripId}`}>{b.route}</Link></TableCell><TableCell>{b.seats}</TableCell><TableCell>{b.amount}</TableCell><TableCell><Badge variant={variant(b.status)}>{b.status}</Badge></TableCell></TableRow>)}</TableBody></Table>:<Empty/>}</Card>
    <Card className="overflow-hidden shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Payments</CardTitle><CardDescription>Payments associated with this passenger.</CardDescription></CardHeader>{payments.length?<Table><TableHeader><TableRow className="hover:bg-transparent"><TableHead>Reference</TableHead><TableHead>Booking</TableHead><TableHead>Amount</TableHead><TableHead>Method</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{payments.map(p=><TableRow key={p.ref}><TableCell><Link className="font-semibold text-[#101828] hover:text-[#1877F2]" href={`/admin/payments/${p.ref}`}>{p.ref}</Link></TableCell><TableCell>{p.booking}</TableCell><TableCell>{p.amount}</TableCell><TableCell>{p.method}</TableCell><TableCell><Badge variant={variant(p.status)}>{p.status}</Badge></TableCell></TableRow>)}</TableBody></Table>:<Empty/>}</Card>
   </div><div className="space-y-6"><Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Activity</CardTitle><CardDescription>Passenger-specific audit history.</CardDescription></CardHeader><ActivityList items={activity}/></Card><Card className="border-[#FECACA] shadow-none"><CardHeader><CardTitle className="text-[#B42318]">Administrative actions</CardTitle><CardDescription>Soft removal preserves booking and payment history.</CardDescription></CardHeader><CardContent><Button variant="destructive" onClick={()=>setRemoveOpen(true)}><Trash2/>Remove passenger</Button></CardContent></Card></div></div>
  </main>
  <Dialog open={editOpen} onOpenChange={setEditOpen}><DialogContent><DialogHeader><DialogTitle>Edit passenger</DialogTitle><DialogDescription>Update account and contact details.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void save(new FormData(e.currentTarget));}}><div className="space-y-4 p-5"><Field label="Full name" id="p-name"><Input id="p-name" name="name" defaultValue={passenger.name} required/></Field><Field label="Email" id="p-email"><Input id="p-email" name="email" type="email" defaultValue={passenger.email} required/></Field><Field label="Phone" id="p-phone"><Input id="p-phone" name="phone" defaultValue={passenger.phone}/></Field><Field label="Home city" id="p-city"><Input id="p-city" name="city" defaultValue={passenger.city} required/></Field></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setEditOpen(false)}>Cancel</Button><Button type="submit" className="bg-[#1877F2]" disabled={saving}>{saving?"Saving...":"Save changes"}</Button></DialogFooter></form></DialogContent></Dialog>
  <Dialog open={removeOpen} onOpenChange={setRemoveOpen}><DialogContent><DialogHeader><DialogTitle>Remove {passenger.name}?</DialogTitle><DialogDescription>Historical bookings and payments remain intact.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setRemoveOpen(false)}>Cancel</Button><Button variant="destructive" onClick={()=>void remove()} disabled={saving}><Trash2/>Remove passenger</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-[#EAECF0] bg-[#F9FAFB] p-4"><div className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#98A2B3]">{label}</div><div className="mt-2 text-sm font-semibold text-[#344054]">{value}</div></div>}
function Field({label,id,children}:{label:string;id:string;children:React.ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
function Empty(){return <div className="grid min-h-28 place-items-center p-6 text-sm text-[#98A2B3]">No related records.</div>}
function ActivityList({items}:{items:Activity[]}){return <CardContent className="divide-y divide-[#EAECF0] p-0">{items.length?items.map(i=><div key={i.id} className="px-5 py-4"><div className="text-xs font-semibold">{i.title}</div><div className="mt-1 text-[11px] text-[#667085]">{i.detail}</div><div className="mt-1 text-[10px] text-[#98A2B3]">{i.time}</div></div>):<div className="p-5 text-xs text-[#98A2B3]">No activity yet.</div>}</CardContent>}
