"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Banknote, CheckCircle2, Pencil, RefreshCcw, RotateCcw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Payment={id:string;publicId:string;amountCents:number;amount:string;method:string;status:string;createdAt:string};
type Booking={id:string;databaseId:string};
type Passenger={id:string;name:string;email:string};
type Trip={id:string;route:string};
type Activity={id:string;title:string;detail:string;time:string};

function variant(v:string){const s=v.toLowerCase();if(s.includes("settled")||s.includes("paid"))return "success" as const;if(s.includes("pending"))return "warning" as const;if(s.includes("refund")||s.includes("failed"))return "destructive" as const;return "secondary" as const;}

export function PaymentDetail({initialPayment,booking,passenger,trip,activity}:{initialPayment:Payment;booking:Booking;passenger:Passenger;trip:Trip;activity:Activity[]}) {
 const router=useRouter(); const [payment,setPayment]=useState(initialPayment); const [editOpen,setEditOpen]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 async function patch(update:Record<string,unknown>){setSaving(true);setMessage(null);try{const r=await fetch(`/api/admin/payments/${payment.publicId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(update)});const p=await r.json().catch(()=>null);if(!r.ok){setMessage(p?.error??"Unable to update payment");return false;}setPayment(c=>({...c,...update,status:String(update.status??c.status),method:String(update.method??c.method)} as Payment));router.refresh();return true;}finally{setSaving(false);}}
 async function save(fd:FormData){const ok=await patch({amount:Number(fd.get("amount")),method:String(fd.get("method")||""),status:String(fd.get("status")||"")});if(ok){setEditOpen(false);setMessage("Payment updated.");}}
 return <div className="min-h-screen bg-[#F7F8FA] text-[#101828]">
 <header className="sticky top-0 z-30 border-b border-[#E4E7EC] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center gap-3 px-4 sm:px-6 lg:px-8"><Button variant="outline" size="icon" render={<Link href="/admin"/>}><ArrowLeft/></Button><div className="min-w-0 flex-1"><div className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#98A2B3]">Vaya CRM / Payments</div><div className="truncate text-sm font-semibold">{payment.publicId}</div></div><Badge variant={variant(payment.status)}>{payment.status}</Badge><Button variant="outline" onClick={()=>setEditOpen(true)}><Pencil/>Edit</Button></div></header>
 <main className="mx-auto max-w-[1200px] p-4 sm:p-6 lg:p-8">{message?<div className="mb-5 rounded-lg border border-[#D1E9FF] bg-[#F5F9FF] px-4 py-3 text-sm text-[#175CD3]">{message}</div>:null}
 <div className="mb-6 flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold text-[#1877F2]"><Banknote className="size-4"/>Payment record</div><h1 className="mt-2 text-2xl font-bold tracking-[-.035em] sm:text-[30px]">{payment.publicId}</h1><p className="mt-2 text-sm text-[#667085]">{payment.amount} · {passenger.name}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void patch({status:"Pending"})}><RefreshCcw/>Pending</Button><Button className="bg-[#1877F2] hover:bg-[#166FE5]" onClick={()=>void patch({status:"Settled"})}><CheckCircle2/>Settle</Button><Button variant="destructive" onClick={()=>void patch({status:"Refunded"})}><RotateCcw/>Refund</Button></div></div>
 <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="space-y-6">
 <Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Payment details</CardTitle><CardDescription>Settlement and transaction information.</CardDescription></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2"><Metric label="Amount" value={payment.amount}/><Metric label="Method" value={payment.method}/><Metric label="Status" value={payment.status}/><Metric label="Created" value={new Date(payment.createdAt).toLocaleString("en-ZA")}/></CardContent></Card>
 <Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Related records</CardTitle><CardDescription>Trace this payment back to its customer and journey.</CardDescription></CardHeader><CardContent className="grid gap-3 p-5 sm:grid-cols-3"><Link className="rounded-lg border border-[#EAECF0] p-4 hover:border-[#B7D5FA] hover:bg-[#F8FBFF]" href={`/admin/bookings/${booking.id}`}><div className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#98A2B3]">Booking</div><div className="mt-2 text-sm font-semibold">{booking.id}</div></Link><Link className="rounded-lg border border-[#EAECF0] p-4 hover:border-[#B7D5FA] hover:bg-[#F8FBFF]" href={`/admin/passengers/${passenger.id}`}><div className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#98A2B3]">Passenger</div><div className="mt-2 text-sm font-semibold">{passenger.name}</div></Link><Link className="rounded-lg border border-[#EAECF0] p-4 hover:border-[#B7D5FA] hover:bg-[#F8FBFF]" href={`/admin/trips/${trip.id}`}><div className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#98A2B3]">Trip</div><div className="mt-2 text-sm font-semibold">{trip.route}</div></Link></CardContent></Card>
 </div><Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Activity</CardTitle><CardDescription>Payment audit history.</CardDescription></CardHeader><CardContent className="divide-y divide-[#EAECF0] p-0">{activity.length?activity.map(i=><div key={i.id} className="px-5 py-4"><div className="text-xs font-semibold">{i.title}</div><div className="mt-1 text-[11px] text-[#667085]">{i.detail}</div><div className="mt-1 text-[10px] text-[#98A2B3]">{i.time}</div></div>):<div className="p-5 text-xs text-[#98A2B3]">No activity yet.</div>}</CardContent></Card></div>
 </main>
 <Dialog open={editOpen} onOpenChange={setEditOpen}><DialogContent><DialogHeader><DialogTitle>Edit payment</DialogTitle><DialogDescription>Update amount, method or reconciliation status.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void save(new FormData(e.currentTarget));}}><div className="space-y-4 p-5"><Field label="Amount" id="pay-amount"><Input id="pay-amount" name="amount" type="number" min="0" step="1" defaultValue={payment.amountCents/100} required/></Field><Field label="Method" id="pay-method"><select id="pay-method" name="method" defaultValue={payment.method} className="h-9 w-full rounded-lg border border-[#D0D5DD] bg-white px-3 text-sm"><option>Card</option><option>Instant EFT</option><option>Cash</option><option>Bank transfer</option></select></Field><Field label="Status" id="pay-status"><select id="pay-status" name="status" defaultValue={payment.status} className="h-9 w-full rounded-lg border border-[#D0D5DD] bg-white px-3 text-sm"><option>Pending</option><option>Settled</option><option>Refunded</option><option>Failed</option></select></Field></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setEditOpen(false)}>Cancel</Button><Button type="submit" className="bg-[#1877F2]" disabled={saving}>{saving?"Saving...":"Save changes"}</Button></DialogFooter></form></DialogContent></Dialog>
 </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-[#EAECF0] bg-[#F9FAFB] p-4"><div className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#98A2B3]">{label}</div><div className="mt-2 text-sm font-semibold text-[#344054]">{value}</div></div>}
function Field({label,id,children}:{label:string;id:string;children:React.ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
