"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, Pencil, ShieldAlert, UserRoundCog, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type SafetyCase={id:string;publicId:string;subject:string;tripLabel:string;priority:string;owner:string;note:string;status:string;createdAt:string;updatedAt:string};
type Trip={id:string;route:string;driver:string;status:string}|null;
type Activity={id:string;title:string;detail:string;time:string};

function variant(v:string){const s=v.toLowerCase();if(s.includes("resolved")||s.includes("closed"))return "success" as const;if(s.includes("investigat")||s.includes("waiting")||s.includes("medium"))return "warning" as const;if(s.includes("high")||s.includes("open"))return "destructive" as const;return "secondary" as const;}

export function SafetyCaseDetail({initialCase,trip,activity}:{initialCase:SafetyCase;trip:Trip;activity:Activity[]}) {
 const router=useRouter(); const [item,setItem]=useState(initialCase); const [editOpen,setEditOpen]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 async function patch(update:Record<string,unknown>){setSaving(true);setMessage(null);try{const r=await fetch(`/api/admin/safety-cases/${item.publicId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(update)});const p=await r.json().catch(()=>null);if(!r.ok){setMessage(p?.error??"Unable to update case");return false;}setItem(c=>({...c,...update,status:String(update.status??c.status),updatedAt:new Date().toISOString()} as SafetyCase));router.refresh();return true;}finally{setSaving(false);}}
 async function save(fd:FormData){const ok=await patch({subject:String(fd.get("subject")||"").trim(),priority:String(fd.get("priority")||""),owner:String(fd.get("owner")||"").trim(),note:String(fd.get("note")||"").trim(),status:String(fd.get("status")||"")});if(ok){setEditOpen(false);setMessage("Safety case updated.");}}
 return <div className="min-h-screen bg-[#F7F8FA] text-[#101828]">
 <header className="sticky top-0 z-30 border-b border-[#E4E7EC] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center gap-3 px-4 sm:px-6 lg:px-8"><Button variant="outline" size="icon" render={<Link href="/admin"/>}><ArrowLeft/></Button><div className="min-w-0 flex-1"><div className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#98A2B3]">Vaya CRM / Safety</div><div className="truncate text-sm font-semibold">{item.publicId}</div></div><Badge variant={variant(item.priority)}>{item.priority}</Badge><Badge variant={variant(item.status)}>{item.status}</Badge><Button variant="outline" onClick={()=>setEditOpen(true)}><Pencil/>Edit</Button></div></header>
 <main className="mx-auto max-w-[1200px] p-4 sm:p-6 lg:p-8">{message?<div className="mb-5 rounded-lg border border-[#D1E9FF] bg-[#F5F9FF] px-4 py-3 text-sm text-[#175CD3]">{message}</div>:null}
 <div className="mb-6 flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold text-[#D92D20]"><ShieldAlert className="size-4"/>{item.publicId}</div><h1 className="mt-2 max-w-3xl text-2xl font-bold tracking-[-.035em] sm:text-[30px]">{item.subject}</h1><p className="mt-2 text-sm text-[#667085]">{item.tripLabel}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void patch({status:"Investigating"})}><UserRoundCog/>Investigate</Button><Button variant="outline" onClick={()=>void patch({status:"Resolved"})}><CheckCircle2/>Resolve</Button><Button className="bg-[#1877F2] hover:bg-[#166FE5]" onClick={()=>void patch({status:"Closed"})}>Close case</Button></div></div>
 <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="space-y-6">
 <Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Case details</CardTitle><CardDescription>Investigation ownership, priority and notes.</CardDescription></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2"><Metric label="Priority" value={item.priority}/><Metric label="Owner" value={item.owner}/><Metric label="Status" value={item.status}/><Metric label="Created" value={new Date(item.createdAt).toLocaleString("en-ZA")}/><div className="sm:col-span-2 rounded-lg border border-[#EAECF0] bg-[#F9FAFB] p-4"><div className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#98A2B3]">Internal note</div><div className="mt-2 text-sm leading-6 text-[#344054]">{item.note||"No internal note."}</div></div></CardContent></Card>
 {trip?<Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Related trip</CardTitle><CardDescription>Journey connected to this case.</CardDescription></CardHeader><CardContent className="p-5"><Link className="block rounded-lg border border-[#EAECF0] p-4 transition hover:border-[#B7D5FA] hover:bg-[#F8FBFF]" href={`/admin/trips/${trip.id}`}><div className="text-sm font-semibold">{trip.route}</div><div className="mt-1 text-xs text-[#667085]">{trip.driver} · {trip.status}</div></Link></CardContent></Card>:null}
 </div><Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Investigation history</CardTitle><CardDescription>Audit trail for this case.</CardDescription></CardHeader><CardContent className="divide-y divide-[#EAECF0] p-0">{activity.length?activity.map(i=><div key={i.id} className="px-5 py-4"><div className="text-xs font-semibold">{i.title}</div><div className="mt-1 text-[11px] text-[#667085]">{i.detail}</div><div className="mt-1 text-[10px] text-[#98A2B3]">{i.time}</div></div>):<div className="p-5 text-xs text-[#98A2B3]">No case activity yet.</div>}</CardContent></Card></div>
 </main>
 <Dialog open={editOpen} onOpenChange={setEditOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Edit safety case</DialogTitle><DialogDescription>Update the investigation record, priority, owner and status.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void save(new FormData(e.currentTarget));}}><div className="grid gap-4 p-5 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Subject" id="s-subject"><Input id="s-subject" name="subject" defaultValue={item.subject} required/></Field></div><Field label="Priority" id="s-priority"><select id="s-priority" name="priority" defaultValue={item.priority} className="h-9 w-full rounded-lg border border-[#D0D5DD] bg-white px-3 text-sm"><option>Low</option><option>Medium</option><option>High</option></select></Field><Field label="Owner" id="s-owner"><Input id="s-owner" name="owner" defaultValue={item.owner}/></Field><Field label="Status" id="s-status"><select id="s-status" name="status" defaultValue={item.status} className="h-9 w-full rounded-lg border border-[#D0D5DD] bg-white px-3 text-sm"><option>Open</option><option>Investigating</option><option>Waiting</option><option>Resolved</option><option>Closed</option></select></Field><div className="sm:col-span-2"><Field label="Internal note" id="s-note"><Textarea id="s-note" name="note" defaultValue={item.note}/></Field></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setEditOpen(false)}>Cancel</Button><Button type="submit" className="bg-[#1877F2]" disabled={saving}>{saving?"Saving...":"Save changes"}</Button></DialogFooter></form></DialogContent></Dialog>
 </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-[#EAECF0] bg-[#F9FAFB] p-4"><div className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#98A2B3]">{label}</div><div className="mt-2 text-sm font-semibold text-[#344054]">{value}</div></div>}
function Field({label,id,children}:{label:string;id:string;children:React.ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
