"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, CalendarClock, CheckCircle2, MapPin, Pencil, Route, ShieldAlert, Users, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Trip={id:string;publicId:string;fromCity:string;toCity:string;driverId:string;driverName:string;departureAt:string;seatCapacity:number;seatsBooked:number;fareCents:number;fare:string;status:string;createdAt:string;updatedAt:string};
type Booking={id:string;passengerId:string;passenger:string;seats:number;amount:string;payment:string;status:string};
type Safety={id:string;subject:string;priority:string;owner:string;status:string};
type Activity={id:string;title:string;detail:string;time:string};

function variant(value:string){const v=value.toLowerCase();if(v.includes("schedule")||v.includes("completed")||v.includes("paid")||v.includes("confirmed"))return "success" as const;if(v.includes("boarding")||v.includes("full")||v.includes("review")||v.includes("waiting"))return "warning" as const;if(v.includes("cancel")||v.includes("suspend")||v.includes("high"))return "destructive" as const;return "secondary" as const;}

export function TripDetail({initialTrip,bookings,safetyCases,activity}:{initialTrip:Trip;bookings:Booking[];safetyCases:Safety[];activity:Activity[]}) {
 const router=useRouter(); const [trip,setTrip]=useState(initialTrip); const [editOpen,setEditOpen]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 async function patch(update:Record<string,unknown>){setSaving(true);setMessage(null);try{const r=await fetch(`/api/admin/trips/${trip.publicId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(update)});const p=await r.json().catch(()=>null);if(!r.ok){setMessage(p?.error??"Unable to update trip");return false;}setTrip(c=>({...c,...update,status:String(update.status??c.status),updatedAt:new Date().toISOString()} as Trip));router.refresh();return true;}finally{setSaving(false);}}
 async function save(fd:FormData){const ok=await patch({fromCity:String(fd.get("fromCity")||"").trim(),toCity:String(fd.get("toCity")||"").trim(),driverName:String(fd.get("driverName")||"").trim(),departureAt:String(fd.get("departureAt")||""),seatCapacity:Number(fd.get("seatCapacity")),fare:Number(fd.get("fare"))});if(ok){setEditOpen(false);setMessage("Trip updated.");}}
 return <div className="min-h-screen bg-[#F7F8FA] text-[#101828]">
 <header className="sticky top-0 z-30 border-b border-[#E4E7EC] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center gap-3 px-4 sm:px-6 lg:px-8"><Button variant="outline" size="icon" render={<Link href="/admin"/>}><ArrowLeft/></Button><div className="min-w-0 flex-1"><div className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#98A2B3]">Vaya CRM / Trips</div><div className="truncate text-sm font-semibold">{trip.publicId}</div></div><Badge variant={variant(trip.status)}>{trip.status}</Badge><Button variant="outline" onClick={()=>setEditOpen(true)}><Pencil/>Edit</Button></div></header>
 <main className="mx-auto max-w-[1440px] p-4 sm:p-6 lg:p-8">{message?<div className="mb-5 rounded-lg border border-[#D1E9FF] bg-[#F5F9FF] px-4 py-3 text-sm text-[#175CD3]">{message}</div>:null}
 <div className="mb-6 flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold text-[#1877F2]"><Route className="size-4"/>{trip.publicId}</div><h1 className="mt-2 text-2xl font-bold tracking-[-.035em] sm:text-[30px]">{trip.fromCity} → {trip.toCity}</h1><div className="mt-2 flex flex-wrap gap-4 text-xs text-[#667085]"><span className="inline-flex items-center gap-1.5"><CalendarClock className="size-3.5"/>{new Date(trip.departureAt).toLocaleString("en-ZA")}</span><span className="inline-flex items-center gap-1.5"><Users className="size-3.5"/>{trip.seatsBooked}/{trip.seatCapacity} seats</span></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void patch({status:"Boarding"})}>Boarding</Button><Button variant="outline" onClick={()=>void patch({status:"Completed"})}><CheckCircle2/>Complete</Button><Button variant="destructive" onClick={()=>void patch({status:"Cancelled"})}><XCircle/>Cancel</Button></div></div>
 <div className="grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><div className="space-y-6">
 <Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Trip details</CardTitle><CardDescription>Operational route, driver and capacity information.</CardDescription></CardHeader><CardContent className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3"><Metric label="Driver" value={trip.driverName}/><Metric label="Departure" value={new Date(trip.departureAt).toLocaleString("en-ZA")}/><Metric label="Fare" value={trip.fare}/><Metric label="Seat capacity" value={String(trip.seatCapacity)}/><Metric label="Booked seats" value={String(trip.seatsBooked)}/><Metric label="Status" value={trip.status}/></CardContent></Card>
 <Card className="overflow-hidden shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Bookings</CardTitle><CardDescription>{bookings.length} passenger bookings on this trip.</CardDescription></CardHeader>{bookings.length?<Table><TableHeader><TableRow className="hover:bg-transparent"><TableHead>Booking</TableHead><TableHead>Passenger</TableHead><TableHead>Seats</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{bookings.map(b=><TableRow key={b.id}><TableCell><Link className="font-semibold text-[#101828] hover:text-[#1877F2]" href={`/admin/bookings/${b.id}`}>{b.id}</Link></TableCell><TableCell><Link className="hover:text-[#1877F2]" href={`/admin/passengers/${b.passengerId}`}>{b.passenger}</Link></TableCell><TableCell>{b.seats}</TableCell><TableCell>{b.amount}</TableCell><TableCell><Badge variant={variant(b.status)}>{b.status}</Badge></TableCell></TableRow>)}</TableBody></Table>:<Empty/>}</Card>
 <Card className="overflow-hidden shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Safety cases</CardTitle><CardDescription>Issues linked to this journey.</CardDescription></CardHeader>{safetyCases.length?<Table><TableHeader><TableRow className="hover:bg-transparent"><TableHead>Case</TableHead><TableHead>Subject</TableHead><TableHead>Priority</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{safetyCases.map(s=><TableRow key={s.id}><TableCell><Link className="font-semibold text-[#101828] hover:text-[#1877F2]" href={`/admin/safety/${s.id}`}>{s.id}</Link></TableCell><TableCell>{s.subject}</TableCell><TableCell><Badge variant={variant(s.priority)}>{s.priority}</Badge></TableCell><TableCell><Badge variant={variant(s.status)}>{s.status}</Badge></TableCell></TableRow>)}</TableBody></Table>:<Empty/>}</Card>
 </div><div className="space-y-6"><Card className="shadow-none"><CardHeader className="border-b border-[#EAECF0]"><CardTitle>Activity</CardTitle><CardDescription>Trip lifecycle and changes.</CardDescription></CardHeader><ActivityList items={activity}/></Card><Card className="shadow-none"><CardHeader><CardTitle>Quick status</CardTitle><CardDescription>Move the trip through its operational lifecycle.</CardDescription></CardHeader><CardContent className="grid gap-2"><Button variant="outline" onClick={()=>void patch({status:"On schedule"})}>On schedule</Button><Button variant="outline" onClick={()=>void patch({status:"Full"})}>Mark full</Button><Button variant="outline" onClick={()=>void patch({status:"Suspended"})}>Suspend</Button></CardContent></Card></div></div>
 </main>
 <Dialog open={editOpen} onOpenChange={setEditOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Edit trip</DialogTitle><DialogDescription>Update route, driver, departure, capacity and fare.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void save(new FormData(e.currentTarget));}}><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="From" id="t-from"><Input id="t-from" name="fromCity" defaultValue={trip.fromCity} required/></Field><Field label="To" id="t-to"><Input id="t-to" name="toCity" defaultValue={trip.toCity} required/></Field><Field label="Driver" id="t-driver"><Input id="t-driver" name="driverName" defaultValue={trip.driverName} required/></Field><Field label="Departure" id="t-departure"><Input id="t-departure" name="departureAt" type="datetime-local" defaultValue={trip.departureAt.slice(0,16)} required/></Field><Field label="Seat capacity" id="t-seats"><Input id="t-seats" name="seatCapacity" type="number" min="1" max="8" defaultValue={trip.seatCapacity} required/></Field><Field label="Fare" id="t-fare"><Input id="t-fare" name="fare" type="number" min="1" step="1" defaultValue={trip.fareCents/100} required/></Field></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setEditOpen(false)}>Cancel</Button><Button type="submit" className="bg-[#1877F2]" disabled={saving}>{saving?"Saving...":"Save changes"}</Button></DialogFooter></form></DialogContent></Dialog>
 </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-[#EAECF0] bg-[#F9FAFB] p-4"><div className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#98A2B3]">{label}</div><div className="mt-2 text-sm font-semibold text-[#344054]">{value}</div></div>}
function Field({label,id,children}:{label:string;id:string;children:React.ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
function Empty(){return <div className="grid min-h-28 place-items-center p-6 text-sm text-[#98A2B3]">No related records.</div>}
function ActivityList({items}:{items:Activity[]}){return <CardContent className="divide-y divide-[#EAECF0] p-0">{items.length?items.map(i=><div key={i.id} className="px-5 py-4"><div className="text-xs font-semibold">{i.title}</div><div className="mt-1 text-[11px] text-[#667085]">{i.detail}</div><div className="mt-1 text-[10px] text-[#98A2B3]">{i.time}</div></div>):<div className="p-5 text-xs text-[#98A2B3]">No activity yet.</div>}</CardContent>}
